using System.Text;

using DevTeam.Broker.Workflow;

namespace DevTeam.Broker.Gates;

public sealed class ContextBundleGate : IGate
{
    public string Name => BuiltinRegistry.ContextBundle;

    public Task<GateResult> RunAsync(GateRequest request, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.FeatureKey))
            return Task.FromResult(GateResult.Fail("context_bundle requires a featureKey", "featureKey input missing"));

        var featureKey = request.FeatureKey;
        var artifactsDir = ArtifactPaths.FeatureDir(request.WorkspacePath, featureKey);
        var manifest = SliceManifestIO.TryRead(ArtifactPaths.ManifestPath(request.WorkspacePath, featureKey));
        if (manifest is null)
            return Task.FromResult(GateResult.Fail("No slice manifest found", "Run scaffold_specs before context_bundle."));

        var brsPath = ArtifactPaths.BrsPath(request.WorkspacePath, featureKey);
        var brsText = File.Exists(brsPath)
            ? File.ReadAllText(brsPath)
            : "(No BRS file)";

        var builder = new StringBuilder();
        builder.Append($"# Context bundle — {featureKey} ({manifest.Title})").AppendLine();
        builder.AppendLine();
        builder.AppendLine("## Approved requirements (BRS contract)");
        builder.AppendLine();
        builder.AppendLine(brsText);
        builder.AppendLine("## Allowed working areas");
        builder.AppendLine();
        builder.AppendLine($"- Backend: `{manifest.CodePathBack}`");
        builder.AppendLine($"- Frontend: `{manifest.CodePathFront}`");
        builder.AppendLine("- Artifacts: `devteam/features/" + featureKey + "/*`");
        if (manifest.Shared.Count > 0)
        {
            builder.AppendLine();
            builder.AppendLine("### Shared files (modify with care)");
            foreach (var shared in manifest.Shared)
                builder.AppendLine($"- `{shared}`");
        }
        builder.AppendLine();
        builder.AppendLine("## Working rules");
        builder.AppendLine("- Implement only what each REQ demands. Do not invent scope.");
        builder.AppendLine("- Add tests first; the verify/code gate runs them and reports failures.");
        builder.AppendLine("- Only edit files under the allowed working areas above.");
        builder.AppendLine();
        builder.Append($"(Generated by DevTeam at {DateTimeOffset.UtcNow:O}.)");

        cancellationToken.ThrowIfCancellationRequested();
        var contextPath = ArtifactPaths.ContextPath(request.WorkspacePath, featureKey);
        Directory.CreateDirectory(artifactsDir);
        File.WriteAllText(contextPath, builder.ToString());

        return Task.FromResult(GateResult.Pass(
            "Wrote context bundle for next stage",
            $"requirements + working rules → {Path.GetRelativePath(request.WorkspacePath, contextPath)}",
            Path.GetRelativePath(request.WorkspacePath, contextPath)));
    }
}