using System.Text;

using DevTeam.Broker.Workflow;

namespace DevTeam.Broker.Gates;

public sealed class RenderPrGate : IGate
{
    private readonly IProcessRunner _runner;

    public RenderPrGate(IProcessRunner runner) => _runner = runner;

    public string Name => BuiltinRegistry.RenderPr;

    public async Task<GateResult> RunAsync(GateRequest request, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.FeatureKey))
            return GateResult.Fail("render_pr requires a featureKey", "featureKey input missing");

        var featureKey = request.FeatureKey;
        var title = GateInputs.Get(request.Inputs, "title", featureKey);
        var manifest = SliceManifestIO.TryRead(ArtifactPaths.ManifestPath(request.WorkspacePath, featureKey));
        if (manifest is not null)
            title = manifest.Title;

        var changedFiles = await GetChangedFilesAsync(request.WorkspacePath, cancellationToken);
        var testOutput = GateInputs.Get(request.Inputs, "testOutput", string.Empty);
        var coverage = GateInputs.Get(request.Inputs, "coverage", "n/a");
        var findings = GateInputs.Get(request.Inputs, "findings", "none open");

        var builder = new StringBuilder();
        builder.Append($"# {featureKey} — {title}: pull request summary").AppendLine();
        builder.AppendLine();
        builder.Append("**Feature:** ").Append(featureKey).AppendLine();
        builder.AppendLine();
        builder.Append("## Changed files").AppendLine();
        builder.AppendLine();
        if (changedFiles.Length == 0)
            builder.AppendLine("_(no tracked changes detected)_");
        else
            foreach (var file in changedFiles)
                builder.AppendLine($"- `{file}`");
        builder.AppendLine();
        builder.Append("## Verification").AppendLine();
        builder.AppendLine();
        builder.AppendLine("```");
        builder.AppendLine(string.IsNullOrWhiteSpace(testOutput) ? "no test output captured" : testOutput);
        builder.AppendLine("```");
        builder.AppendLine();
        builder.Append("## Requirement coverage").AppendLine();
        builder.AppendLine();
        builder.AppendLine("```");
        builder.AppendLine(coverage);
        builder.AppendLine("```");
        builder.AppendLine();
        builder.Append("## Open findings").AppendLine();
        builder.AppendLine();
        builder.AppendLine(findings);
        builder.AppendLine();
        builder.Append($"(Generated by DevTeam at {DateTimeOffset.UtcNow:O})");

        cancellationToken.ThrowIfCancellationRequested();
        var path = Path.Combine(ArtifactPaths.FeatureDir(request.WorkspacePath, featureKey), $"PR-{featureKey}.md");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, builder.ToString());

        return GateResult.Pass(
            "Rendered pull request summary",
            $"{Path.GetRelativePath(request.WorkspacePath, path)} ({changedFiles.Length} changed files)",
            Path.GetRelativePath(request.WorkspacePath, path));
    }

    private async Task<string[]> GetChangedFilesAsync(string workspacePath, CancellationToken cancellationToken)
    {
        var diff = await _runner.RunAsync(
            new ProcessRunRequest("git", "diff --name-only HEAD", workspacePath),
            cancellationToken);
        if (diff.ExitCode != 0)
            return [];

        return diff.StandardOutput
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToArray();
    }
}